name: galaxy_quest
description: A new Flutter project.

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=3.0.6 <4.0.0'

dependencies:
  webview_flutter_plus: ^0.3.0+2
  flame: 1.8.2
  flame_audio: 2.0.5
  provider: 6.0.5
  flutter_carousel_slider: 1.1.0
  hive: 2.2.3
  hive_generator: 2.0.1
  path_provider: 2.1.0
  flutter:
    sdk: flutter
  hive_flutter: 1.1.0
  flutter_html: 3.0.0-beta.2




  cupertino_icons: ^1.0.2
  model_viewer_plus: 1.5.0
  webview_universal: ^0.0.1
  webview_flutter_web: ^0.1.0+4
  fwfh_webview: ^0.6.2+5
  flutter_dotenv: ^5.1.0
  http: ^1.1.0
  dash_chat_2: ^0.0.19
  chat_gpt_sdk: ^2.2.5


dev_dependencies:
  build_runner: 2.4.6
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.9.1
  

  
  flutter_lints: ^2.0.0



flutter:

 
  uses-material-design: true

  assets:
    - assets/solarsystem.glb
    - assets/images/
    - assets/images/team.png
    - assets/team.png
    - assets/audio/
    - assets/game/
    - quizapp/index.html
    - assets/images/nasa.png

  
  

  fonts:
    - family: Monteserrat
      fonts:
        - asset: assets/fonts/Montserrat-VariableFont_wght.ttf
